### ISSUE TITLE
Implement a <projectname>.wpp.targets file

### ISSUE THREAD

**Issue by ajbrun** [netconstruct/generator-netconstruct#10]
Implement a <projectname>.wpp.targets file is that front end dist files are published without needing to manually edit them project for each new site.

The Yeoman generator will need to ask for the main project name and the location of the dist files if it doesn't know it already.

http://chris.59north.com/post/Setting-Up-Continuous-Deployment-of-an-ASPNET-App-with-Gulp-from-VSTS-to-an-Azure-Web-App-using-Scripted-Build-Definitions

**Comment by rshackleton-netc** [comment]
Interesting, need to check the existing build and deployment process will use the .wpp.targets file first.

**Comment by rshackleton** [comment]
Tested the use of the file in the build process, worked correct so will look at having this included in the generator.

**Comment by ajbrun** [comment]
`<?xml version="1.0" encoding="utf-8" ?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">  
  <Target Name="AddGulpFiles" BeforeTargets="CopyAllFilesToSingleFolderForPackage;CopyAllFilesToSingleFolderForMsdeploy">
    <Message Text="Adding gulp-generated files to deploy" Importance="high"/>
    <ItemGroup>
      <NetCDistFilesToInclude Include="SiteFiles\dist\**\*" />
      <FilesForPackagingFromProject Include="%(NetCDistFilesToInclude.Identity)">
        <DestinationRelativePath>SiteFiles\dist\%(RecursiveDir)%(Filename)%(Extension)</DestinationRelativePath>
      </FilesForPackagingFromProject>
    </ItemGroup>
  </Target>
</Project>`
